services:
  # 1. The Frontend Application
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      # Syncs your local folder to the container's /app folder
      - ./webapp:/app
      # Prevents the container's node_modules from being overwritten by your local (possibly empty) one
      - /app/node_modules
    ports:
      - "4242:3000"
    environment:
      - VITE_CDN_URL=http://localhost:8080
      # ENSURES HOT RELOAD WORKS:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - cdn

  # 2. The Data Pipeline (ETL)
  pipeline:
    build: 
      context: ./pipeline
      dockerfile: Dockerfile
    volumes:
      - ./data_out:/output
    command: python etl_job.py

  # 3. The Local CDN (Simulating S3)
  cdn:
    image: nginx:alpine
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data_out:/usr/share/nginx/html/data
    ports:
      - "4343:80"
