import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { parseDNAFile } from '../src/parser/parse.js';

describe('parseDNAFile', () => {
  it('parses a 23andMe file', () => {
    const text = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs12345\t1\t100\tAG',
      'rs67890\t2\t200\tTT',
      'rs11111\t3\t300\tCC',
    ].join('\n');

    const result = parseDNAFile(text);
    assert.equal(result.format, '23andMe');
    assert.equal(result.variants.length, 3);
    assert.equal(result.variants[0].rsid, 'rs12345');
    assert.equal(result.variants[0].allele1, 'A');
    assert.equal(result.variants[0].allele2, 'G');
  });

  it('parses an AncestryDNA file', () => {
    const text = [
      '#AncestryDNA raw data',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs100\t1\t500\tA\tG',
      'rs200\t2\t600\tT\tC',
    ].join('\n');

    const result = parseDNAFile(text);
    assert.equal(result.format, 'AncestryDNA');
    assert.equal(result.variants.length, 2);
  });

  it('returns unknown for unrecognized format', () => {
    const result = parseDNAFile('just some random text\nmore text\n');
    assert.equal(result.format, 'unknown');
    assert.equal(result.variants.length, 0);
  });

  it('skips blank lines and invalid rows', () => {
    const text = [
      '# This data file generated by 23andMe',
      '',
      'rs1\t1\t100\tAG',
      '',
      'rs2\tMT\t200\tAG',
      'rs3\t2\t300\tCC',
    ].join('\n');

    const result = parseDNAFile(text);
    assert.equal(result.variants.length, 2);
  });

  it('calls onProgress during parsing', () => {
    const lines = ['# This data file generated by 23andMe'];
    for (let i = 0; i < 100; i++) {
      lines.push(`rs${i}\t1\t${i + 1}\tAG`);
    }

    let progressCalls = 0;
    parseDNAFile(lines.join('\n'), () => { progressCalls++; });
    assert.ok(progressCalls >= 1);
  });

  it('reports skipped count', () => {
    const text = [
      '# This data file generated by 23andMe',
      'rs1\t1\t100\tAG',
      'bad line without tabs',
      'rs2\t2\t200\tCC',
    ].join('\n');

    const result = parseDNAFile(text);
    assert.equal(result.variants.length, 2);
    assert.equal(result.skipped, 1);
  });
});
