import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { detectFormat } from '../src/parser/detect.js';

describe('detectFormat', () => {
  it('detects 23andMe from "# This data"', () => {
    assert.equal(detectFormat('# This data file generated by 23andMe\n'), '23andMe');
  });

  it('detects 23andMe from "# rsid"', () => {
    assert.equal(detectFormat('# rsid\tchromosome\tposition\tgenotype\n'), '23andMe');
  });

  it('detects AncestryDNA', () => {
    assert.equal(
      detectFormat('#AncestryDNA\nrsid\tchromosome\tposition\tallele1\tallele2\n'),
      'AncestryDNA',
    );
  });

  it('detects MyHeritage CSV', () => {
    assert.equal(detectFormat('RSID,CHROMOSOME,POSITION,RESULT\n'), 'MyHeritage');
  });

  it('detects MyHeritage TSV', () => {
    assert.equal(detectFormat('RSID\tCHROMOSOME\tPOSITION\tRESULT\n'), 'MyHeritage');
  });

  it('detects FamilyTreeDNA', () => {
    assert.equal(detectFormat('RSID\tCHROMOSOME\tPOSITION\tALLELE1\tALLELE2\n'), 'FamilyTreeDNA');
  });

  it('detects VCF', () => {
    assert.equal(detectFormat('##fileformat=VCFv4.2\n#CHROM\tPOS\n'), 'VCF');
  });

  it('returns unknown for unrecognized format', () => {
    assert.equal(detectFormat('some random text\n'), 'unknown');
  });
});
